export interface Itens {
    numero: string,
    empresa: string,
    produto: string,
    descricaoProduto: string,
    quantidade: number,
    preco: number,
    total: number,
    estoque: number,
    desconto: number,
    valorDesconto: number,
    tipoEntrega: string,
    codigoBarras: string,
    armazem: string,
}